name: GitHub Pages

on:
  pull_request:
    branches:
      - document-src
  push:
    branches:
      - document-src

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test Build
        env:
          COMPONENT_PATH: ../docusaurus/docs/components
          DOCUSAURUS_PATH: ../docusaurus
          SUPERNOVA_PATH: supernova
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          cd docusaurus && yarn install && cd ../
          cd supernova && yarn install && cd ../
          yarn gen-md
          yarn build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          CURRENT_BRANCH: document-src
          COMPONENT_PATH: ../docusaurus/docs/components
          DOCUSAURUS_PATH: ../docusaurus
          SUPERNOVA_PATH: supernova
        run: |
          git config --global user.email "s-hayashi@creationline.com"
          git config --global user.name "CreationLine"
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          cd docusaurus && yarn install && cd ../
          cd supernova && yarn install && cd ../
          yarn gen-md
          yarn deploy
